/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.IOFile;
import java.io.File;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DSThuePhong;
import model.KhachHang;
import model.Phong;

/**
 *
 * @author Admin
 */
public class FormDSTP extends javax.swing.JPanel {

    /**
     * Creates new form FormDSThuePhong
     */
    private DefaultTableModel tm;
    private String file;
    private boolean ok;
    
    public FormDSTP() {
        initComponents();
        setSize(900,500);
        file = "src/controller/DSTP.DAT";
        ok = false;
        String cols[]={"Ma KH", "Ten KH", "Ma Phong","Ten phong","Thoi gian thue"};
        tm=new DefaultTableModel(cols, 0);
        jTable1.setModel(tm);
        addItem();
    }

    private void addItem() {
        jComboBox1.removeAllItems();
        List<KhachHang> a = IOFile.doc("src/controller/KH.DAT");
        for(KhachHang i:a) {
            jComboBox1.addItem(i.getMa()+"");
        }
        
        jComboBox2.removeAllItems();
        List<Phong> a1 = IOFile.doc("src/controller/PHONG.DAT");
        for(Phong i:a1) {
            jComboBox2.addItem(i.getMa()+"");
        }
    }
    
    private KhachHang getKHByMa(int ma) {
        List<KhachHang> a = IOFile.doc("src/controller/KH.DAT");
        for(KhachHang i:a) {
            if(i.getMa()==ma) return i;
        }
        return null;
    }
    private Phong getPByMa(int ma) {
        List<Phong> a1 = IOFile.doc("src/controller/PHONG.DAT");
        for(Phong i:a1) {
            if(i.getMa()==ma) return i;
        }
        return null;
    }
    
    private boolean Check(int maK, int maP, String time) {
        for(int i=0;i<tm.getRowCount();i++){
            if(tm.getValueAt(i, 0).toString().equalsIgnoreCase(maK+"")) {
                if(tm.getValueAt(i, 2).toString().equalsIgnoreCase(maP+""))
                    return false;
                if(tm.getValueAt(i, 4).toString().equalsIgnoreCase(time))
                    return false;
            }
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Them");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lam moi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cap nhat");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Luu file");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Hien thi");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ma KH");

        jLabel2.setText("Ma phong");

        jLabel3.setText("Ngay thue");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinh viên", "Hộ gia đình", "Doanh nghiệp" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Ten KH");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ten phong");

        jButton6.setText("Sap xep");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton4))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton5))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jRadioButton2))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jButton2)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addItem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(Check(Integer.parseInt(jComboBox1.getSelectedItem().toString()),
                Integer.parseInt(jComboBox2.getSelectedItem().toString()),
                jTextField1.getText())) {
            KhachHang k = getKHByMa(Integer.parseInt(jComboBox1.getSelectedItem().toString()));
            Phong p =getPByMa(Integer.parseInt(jComboBox2.getSelectedItem().toString()));
            String t = jTextField1.getText();
            tm.addRow(new DSThuePhong(k, p, t).toObject());
        }
        else {
            JOptionPane.showMessageDialog(this, "Nhap du lieu sai!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        List<DSThuePhong> list=new ArrayList<>();
        for (int i = 0; i < tm.getRowCount(); i++) {
            KhachHang k = getKHByMa(Integer.parseInt(tm.getValueAt(i, 0).toString()));
            Phong p =getPByMa(Integer.parseInt(tm.getValueAt(i, 2).toString()));
            String t = tm.getValueAt(i, 4).toString();
            list.add(new DSThuePhong(k, p, t));
        }
        IOFile.viet(file, list);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        List<DSThuePhong> list=IOFile.doc(file);
        tm.setRowCount(0);
        for(DSThuePhong i:list) {
            tm.addRow(i.toObject());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        addItem();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void sortNameKH() {
        List<DSThuePhong> list = IOFile.doc(file);
        tm.setRowCount(0);
        list.sort(new Comparator<DSThuePhong>() {
            @Override
            public int compare(DSThuePhong o1, DSThuePhong o2) {
                String s1=o1.getKhachHang().getTen();
                String s2=o2.getKhachHang().getTen();
                String t1=s1.substring(s1.lastIndexOf(" ") +1)+s1;
                String t2=s2.substring(s2.lastIndexOf(" ")+1)+s2;
                return t1.compareToIgnoreCase(t2);
            }
        });
        for(DSThuePhong i:list) {
            tm.addRow(i.toObject());
        }
    }
    
    private void sortNameP() {
        List<DSThuePhong> list = IOFile.doc(file);
        tm.setRowCount(0);
        list.sort(new Comparator<DSThuePhong>() {
            @Override
            public int compare(DSThuePhong o1, DSThuePhong o2) {
                String s1=o1.getPhong().getTen();
                String s2=o2.getPhong().getTen();
                
                return s1.compareToIgnoreCase(s2);
            }
        });
        for(DSThuePhong i:list) {
            tm.addRow(i.toObject());
        }
    }
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()) 
            sortNameKH();
        else sortNameP();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
